export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const GET_VIDEOGAME_NAME = "GET_VIDEOGAME_NAME";
export const GET_DETAIL_VIDEOGAME = "GET_DETAIL_VIDEOGAME";
export const POST_VIDEOGAME = "POST_VIDEOGAME";

export const GET_PLATFORMS = "GET_PLATFORMS";

export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const FILTER_CREATED = "FILTER_CREATED";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_RATING = "ORDER_BY_RATING";
export const GET_GENRES = "GET_GENRES";
